### ISSUE TITLE
User Limit For Temp Channels

### ISSUE THREAD

**Issue by r3v0lution** [The-Tasty-Jaffa/Tasty-Jaffa-cogs#40]
Curious about the chance of adding user limit to the temp voice channel.

Just something when you run command to create the temp channel:

[p]voice 'channel name' 'user limit'

**Comment by The-Tasty-Jaffa** [comment]
I'm not planning on adding a command (or a parameter) to allow someone to set a user limit, This is because the user who created the channel can go into discords interface and can
- Change the name of the channel
- Change the bit rate of the channel
- **most importantly in this case** Can change the user limit for that channel

**Comment by r3v0lution** [comment]
Ok, thats fair. I help with a community server, and to keep down on all the jumbled up channels, we were trying to allow ANYONE to create the temp channel for whatever purpose. I didn't think that they would be able to change the limit unless they had to manage channels toggle for that specific role..

Anyways, other than that, your cog does exactly what we need! Thx

**Comment by The-Tasty-Jaffa** [comment]
No problem! It uses the "manage channel" permission so it's specific for that channel only.
Any other issues or suggestions feel free to make a git issue!

**Comment by The-Tasty-Jaffa** [comment]
Also:- you may want to update your cogs as I found a different issue related to discord permissions.
